use crate::*;

//================================-================================-================================
#[derive(Default, Eq, PartialEq, Clone, Copy)]
pub enum WeaponType {
    Hammer,
    Sword,
    Axe,
    Pickaxe,
    Katana,
    HolyHandgunOfAntinuk,
    #[default]
    WeakMonsterClaw,
    StandardMonsterClaw,
    RapidMonsterClaw,
    LargeMonsterClaw,
    HeavyMonsterClaw,
    IkthillionsMonsterClaw,

    Null,
}

impl WeaponType {
    pub fn get_def(
        &self,
    ) -> &'static WeaponTypeDef {
        &WEAPON_TYPE_DEFS[*self as usize]
    }
}

pub enum DamageType {
    Blunt,
    Sharp,
}

pub enum AttackType {
    Light,
    Heavy,
}

pub struct WeaponTypeDef {
    pub name: &'static str,
    pub attack_recovery: f32,
    pub attack_delay: f32,
    pub attack_type: AttackType,
    pub crit_chance: f32,
    pub crit_power: f32,
    pub damage: f32,
    pub damage_type: DamageType,
    pub stamina_use: f32,
    
    pub scene: SceneAsset,
    pub attack_sound: SoundAsset,
    pub attack_volume: f32,
    pub attack_offset: Vec3,
    pub attack_anim_speed: f32,
    pub equip_offset: Vec3,
    pub equip_rotation: (Vec3, Vec3),
}

pub const WEAPON_TYPE_DEFS: &'static [WeaponTypeDef] = &[
    WeaponTypeDef {
        name: "Hammer",
        attack_recovery: 400.0,
        attack_delay: 400.0,
        attack_type: AttackType::Light,
        crit_chance: 0.01,
        crit_power: 2.0,
        damage: 3.0,
        damage_type: DamageType::Blunt,
        stamina_use: 10.0,

        scene: SceneAsset::Hammer,
        attack_sound: SoundAsset::Swing00,
        attack_volume: 0.1,
        attack_offset: Vec3::new(0.0, -0.1, -0.2),
        attack_anim_speed: 10.0,
        equip_offset: Vec3::new(0.3, -0.3, -0.5),
        equip_rotation: (Vec3::NEG_Y, Vec3::Z),
    },
    WeaponTypeDef {
        name: "Sword",
        attack_recovery: 175.0,
        attack_delay: 200.0,
        attack_type: AttackType::Light,
        crit_chance: 0.1,
        crit_power: 2.0,
        damage: 6.0,
        damage_type: DamageType::Sharp,
        stamina_use: 20.0,

        scene: SceneAsset::Sword,
        attack_sound: SoundAsset::Swing00,
        attack_volume: 0.1,
        attack_offset: Vec3::new(0.0, -0.2, -0.4),
        attack_anim_speed: 13.0,
        equip_offset: Vec3::new(0.3, -0.6, -0.5),
        equip_rotation: (Vec3::NEG_Y, Vec3::Z),
    },
    WeaponTypeDef {
        name: "Axe",
        attack_recovery: 100.0,
        attack_delay: 250.0,
        attack_type: AttackType::Heavy,
        crit_chance: 0.05,
        crit_power: 2.0,
        damage: 20.0,
        damage_type: DamageType::Sharp,
        stamina_use: 30.0,
        
        scene: SceneAsset::Axe,
        attack_sound: SoundAsset::Swing00,
        attack_volume: 0.1,
        attack_offset: Vec3::new(0.0, -0.1, -0.4),
        attack_anim_speed: 10.0,
        equip_offset: Vec3::new(0.3, -0.5, -0.5),
        equip_rotation: (Vec3::NEG_Y, Vec3::Z),
    },
    WeaponTypeDef {
        name: "Pickaxe",
        attack_recovery: 150.0,
        attack_delay: 300.0,
        attack_type: AttackType::Heavy,
        crit_chance: 0.05,
        crit_power: 2.0,
        damage: 7.0,
        damage_type: DamageType::Sharp,
        stamina_use: 25.0,
        
        scene: SceneAsset::Pickaxe,
        attack_sound: SoundAsset::Swing00,
        attack_volume: 0.1,
        attack_offset: Vec3::new(0.0, -0.1, -0.4),
        attack_anim_speed: 11.0,
        equip_offset: Vec3::new(0.3, -0.4, -0.5),
        equip_rotation: (Vec3::NEG_Y, Vec3::Z),
    },
    WeaponTypeDef {
        name: "Katana",
        attack_recovery: 200.0,
        attack_delay: 400.0,
        attack_type: AttackType::Light,
        crit_chance: 0.35,
        crit_power: 3.0,
        damage: 8.0,
        damage_type: DamageType::Sharp,
        stamina_use: 20.0,
        
        scene: SceneAsset::Katana,
        attack_sound: SoundAsset::Katana00,
        attack_volume: 0.2,
        attack_offset: Vec3::new(0.0, -0.2, -0.4),
        attack_anim_speed: 14.0,
        equip_offset: Vec3::new(0.3, -0.6, -0.5),
        equip_rotation: (Vec3::NEG_Y, Vec3::Z),
    },
    WeaponTypeDef {
        name: "HolyHandgunOfAntinuk",
        attack_recovery: 600.0,
        attack_delay: 600.0,
        attack_type: AttackType::Light,
        crit_chance: 0.2,
        crit_power: 1.5,
        damage: 40.0,
        damage_type: DamageType::Sharp,
        stamina_use: 0.0,
        
        scene: SceneAsset::HolyHandgunOfAntinuk,
        attack_sound: SoundAsset::HolyHandgunOfAntinuk02,
        attack_volume: 0.5,
        attack_offset: Vec3::new(0.0, 0.05, 0.05),
        attack_anim_speed: 15.0,
        equip_offset: Vec3::new(0.3, -0.3, -0.5),
        equip_rotation: (Vec3::Z, Vec3::Y),
    },
    WeaponTypeDef {
        name: "Weak Monster Claw",
        attack_recovery: 15.0,
        attack_delay: 600.0,
        attack_type: AttackType::Light,
        crit_chance: 0.0,
        crit_power: 1.0,
        damage: 5.0,
        damage_type: DamageType::Sharp,
        stamina_use: 4.0,
        
        scene: SceneAsset::Null,
        attack_sound: SoundAsset::FastSwing00,
        attack_volume: 0.1,
        attack_offset: Vec3::new(0.0, 0.0, 0.0),
        attack_anim_speed: 40.0,
        equip_offset: Vec3::ZERO,
        equip_rotation: (Vec3::ZERO, Vec3::ZERO),
    },
    WeaponTypeDef {
        name: "Standard Monster Claw",
        attack_recovery: 7.5,
        attack_delay: 600.0,
        attack_type: AttackType::Light,
        crit_chance: 0.01,
        crit_power: 2.0,
        damage: 10.0,
        damage_type: DamageType::Sharp,
        stamina_use: 5.0,
        
        scene: SceneAsset::Null,
        attack_sound: SoundAsset::FastSwing00,
        attack_volume: 0.1,
        attack_offset: Vec3::new(0.0, 0.0, 0.0),
        attack_anim_speed: 40.0,
        equip_offset: Vec3::ZERO,
        equip_rotation: (Vec3::ZERO, Vec3::ZERO),
    },
    WeaponTypeDef {
        name: "Rapid Monster Claw",
        attack_recovery: 300.0,
        attack_delay: 600.0,
        attack_type: AttackType::Light,
        crit_chance: 0.1,
        crit_power: 2.0,
        damage: 1.0,
        damage_type: DamageType::Sharp,
        stamina_use: 2.5,
        
        scene: SceneAsset::Null,
        attack_sound: SoundAsset::FastSwing00,
        attack_volume: 0.1,
        attack_offset: Vec3::new(0.0, 0.0, 0.0),
        attack_anim_speed: 40.0,
        equip_offset: Vec3::ZERO,
        equip_rotation: (Vec3::ZERO, Vec3::ZERO),
    },
    WeaponTypeDef {
        name: "Large Monster Claw",
        attack_recovery: 2.5,
        attack_delay: 600.0,
        attack_type: AttackType::Heavy,
        crit_chance: 0.025,
        crit_power: 2.0,
        damage: 20.0,
        damage_type: DamageType::Blunt,
        stamina_use: 10.0,
        
        scene: SceneAsset::Null,
        attack_sound: SoundAsset::FastSwing00,
        attack_volume: 0.1,
        attack_offset: Vec3::new(0.0, 0.0, 0.0),
        attack_anim_speed: 40.0,
        equip_offset: Vec3::ZERO,
        equip_rotation: (Vec3::ZERO, Vec3::ZERO),
    },
    WeaponTypeDef {
        name: "Heavy Monster Claw",
        attack_recovery: 0.75,
        attack_delay: 600.0,
        attack_type: AttackType::Heavy,
        crit_chance: 0.05,
        crit_power: 2.0,
        damage: 40.0,
        damage_type: DamageType::Blunt,
        stamina_use: 15.0,
        
        scene: SceneAsset::Null,
        attack_sound: SoundAsset::FastSwing00,
        attack_volume: 0.1,
        attack_offset: Vec3::new(0.0, 0.0, 0.0),
        attack_anim_speed: 40.0,
        equip_offset: Vec3::ZERO,
        equip_rotation: (Vec3::ZERO, Vec3::ZERO),
    },
    WeaponTypeDef {
        name: "Ikthillion's Monster Claw",
        attack_recovery: 0.5,
        attack_delay: 600.0,
        attack_type: AttackType::Light,
        crit_chance: 0.35,
        crit_power: 2.0,
        damage: 45.0,
        damage_type: DamageType::Sharp,
        stamina_use: 5.5,
        
        scene: SceneAsset::Null,
        attack_sound: SoundAsset::IkthillionAttack00,
        attack_volume: 0.4,
        attack_offset: Vec3::new(0.0, 0.0, 0.0),
        attack_anim_speed: 40.0,
        equip_offset: Vec3::ZERO,
        equip_rotation: (Vec3::ZERO, Vec3::ZERO),
    },
];

//================================-================================-================================
#[derive(Eq, PartialEq, Clone, Copy)]
pub enum InventoryItemType {
    Ramen,
    Hammer,
    Sword,
    Axe,
    Pickaxe,
    Katana,
    HolyHandgunOfAntinuk,
}

pub struct InventoryItemTypeDef {
    pub name: &'static str,
    pub weapon_type: WeaponType,
    pub image: ImageAsset,
    pub pickup_sound: SoundAsset,
    pub equip_sound: SoundAsset,
}

pub const INVENTORY_ITEM_TYPE_DEFS: [InventoryItemTypeDef; 7] = [
    InventoryItemTypeDef {
        name: "Ramen",
        weapon_type: WeaponType::Null,
        image: ImageAsset::Ramen,
        pickup_sound: SoundAsset::Tick00,
        equip_sound: SoundAsset::Tick01,
    },
    InventoryItemTypeDef {
        name: "Hammer",
        weapon_type: WeaponType::Hammer,
        image: ImageAsset::Hammer,
        pickup_sound: SoundAsset::Tick00,
        equip_sound: SoundAsset::Tick01,
    },
    InventoryItemTypeDef {
        name: "Sword",
        weapon_type: WeaponType::Sword,
        image: ImageAsset::Sword,
        pickup_sound: SoundAsset::Tick00,
        equip_sound: SoundAsset::Tick01,
    },
    InventoryItemTypeDef {
        name: "Axe",
        weapon_type: WeaponType::Axe,
        image: ImageAsset::Axe,
        pickup_sound: SoundAsset::Tick00,
        equip_sound: SoundAsset::Tick01,
    },
    InventoryItemTypeDef {
        name: "Pickaxe",
        weapon_type: WeaponType::Pickaxe,
        image: ImageAsset::Pickaxe,
        pickup_sound: SoundAsset::Tick00,
        equip_sound: SoundAsset::Tick01,
    },
    InventoryItemTypeDef {
        name: "Katana",
        weapon_type: WeaponType::Katana,
        image: ImageAsset::Katana,
        pickup_sound: SoundAsset::Tick00,
        equip_sound: SoundAsset::Tick01,
    },
    InventoryItemTypeDef {
        name: "Holy Handgun of Antinuk",
        weapon_type: WeaponType::HolyHandgunOfAntinuk,
        image: ImageAsset::HolyHandgunOfAntinuk,
        pickup_sound: SoundAsset::Tick00,
        equip_sound: SoundAsset::HolyHandgunOfAntinuk03,
    },
];